export const SEARCH_GOOGLE_REQUEST = "SEARCH_GOOGLE_REQUEST";
export const SEARCH_GOOGLE_RECEIVE = "SEARCH_GOOGLE_RECEIVE";
export const SEARCH_BING_REQUEST = "SEARCH_BING_REQUEST";
export const SEARCH_BING_RECEIVE = "SEARCH_BING_RECEIVE";
